### ISSUE TITLE
Not working with latest HA  2022.2.1

### ISSUE THREAD

**Issue by Sleepy81** [jxlarrea/ha-emfitqs#6]
Stopped working with latest HA.
Get the following error message when checking configuration:

Platform error binary_sensor.emfitqs - cannot import name 'BinarySensorDevice' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)

**Comment by jxlarrea** [comment]
Fixed in newer version.
